-- Align identity columns with the Java domain model and current registration rules.
ALTER TABLE Accounts
    MODIFY COLUMN USER_NAME VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    MODIFY COLUMN ENCRYTED_PASSWORD VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    MODIFY COLUMN EMAIL VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    ADD CONSTRAINT UK_ACCOUNTS_EMAIL UNIQUE (EMAIL);

ALTER TABLE Products
    MODIFY COLUMN OWNER_USERNAME VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
        NOT NULL DEFAULT 'manager1';

ALTER TABLE Orders
    MODIFY COLUMN CUSTOMER_USERNAME VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
