name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Kịch bản này sẽ chạy mỗi khi có code mới được đẩy lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH vào AWS và chạy lệnh Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd shoeshop
            git pull origin main
            docker compose down --remove-orphans
            docker compose up -d --build

##